version: '3.8'

services:
  server:
    container_name: web-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports: 
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
    env_file: .env
    networks: 
      - primary
    depends_on:
      - psql 

  psql:
    container_name: postgres
    image: postgres:16.1-alpine
    restart: on-failure
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-community}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    networks:
      - primary

volumes:
  db:
networks:
  primary:
